--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/GiftCodeID-GB
build-by-default: true
branches:
- master
projects:
  GiftCodeID-GB:
    path: ""
    libs:
- src: jojoe77777/FormAPI/libFormAPI
...
